# =========================================================================
# CDC gRPC Support / Soporte para gRPC
# =========================================================================
# Usage / Uso: include /opt/nginx/conf/conf.d/domains/includes/proxy-grpc.conf;

# gRPC requires HTTP/2 / gRPC obliga y exige nativamente el uso de HTTP/2
# We configure basic routing parameters / Configuramos parámetros básicos de enrutamiento
grpc_set_header Host $host;
grpc_set_header X-Real-IP $remote_addr;
grpc_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

# Timeouts for gRPC
grpc_connect_timeout 5s;
grpc_send_timeout 60s;
grpc_read_timeout 60s;
