# =========================================================================
# Base Acme Challenge / Configuración de Desafío ACME
# =========================================================================
# Used for Let's Encrypt certificate validation.
# Utilizado para la validación de certificados de Let's Encrypt.

location ^~ /.well-known/acme-challenge/ {
    alias $cdc_challenge_root/.well-known/acme-challenge/;
    default_type "text/plain";
    try_files $uri =404;
}
