package nginx

import (
	"fmt"
	"nginx-cmd/internal/config"
	"os"
	"path/filepath"
	"text/template"
)

const SPATemplate = `
# {{.Domain}}
# Type / Tipo: SPA
# Generated by / Generado por: nginx-cmd

server {
    listen 80;
    listen [::]:80;
    server_name {{.Domain}};
    
    set $cdc_challenge_root {{.SitePath}}/{{.Domain}};
    include {{.NginxPath}}/conf/conf.d/base-acme-challenge.conf;
    
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name {{.Domain}};
    
    ssl_certificate     {{.CertsPath}}/live/{{.Domain}}/fullchain.pem;
    ssl_certificate_key {{.CertsPath}}/live/{{.Domain}}/privkey.pem;
    
    include {{.NginxPath}}/conf/conf.d/base-ssl-config.conf;
    include {{.NginxPath}}/conf/conf.d/base-security-headers.conf;
    
    root {{.SitePath}}/{{.Domain}};
    index index.html index.htm;
    
    location / {
        try_files $uri $uri/ /index.html;
    }
}
`

const ProxyTemplate = `
# {{.Domain}}
# Type / Tipo: Reverse Proxy
# Target / Destino: {{.Target}}
# WebSockets: {{ if .WS }}Enabled / Habilitado{{ else }}Disabled / Deshabilitado{{ end }}
# gRPC: {{ if .GRPC }}Enabled / Habilitado{{ else }}Disabled / Deshabilitado{{ end }}
# Streaming HTTP: {{ if .Stream }}Enabled / Habilitado{{ else }}Disabled / Deshabilitado{{ end }}
# Generated by / Generado por: nginx-cmd

server {
    listen 80;
    listen [::]:80;
    server_name {{.Domain}};
    
    set $cdc_challenge_root {{.SitePath}}/{{.Domain}};
    include {{.NginxPath}}/conf/conf.d/base-acme-challenge.conf;
    
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name {{.Domain}};
    
    ssl_certificate     {{.CertsPath}}/live/{{.Domain}}/fullchain.pem;
    ssl_certificate_key {{.CertsPath}}/live/{{.Domain}}/privkey.pem;
    
    include {{.NginxPath}}/conf/conf.d/base-ssl-config.conf;
    include {{.NginxPath}}/conf/conf.d/base-security-headers.conf;

    location / {
        {{ if .GRPC }}grpc_pass grpc://{{.Target}};
        include {{.NginxPath}}/conf/conf.d/domains/includes/proxy-grpc.conf;
        {{ else }}proxy_pass http://{{.Target}};
        include {{.NginxPath}}/conf/conf.d/domains/includes/proxy-defaults.conf;
        include {{.NginxPath}}/conf/conf.d/domains/includes/proxy-fault-tolerance.conf;
        {{ if .WS }}include {{.NginxPath}}/conf/conf.d/domains/includes/proxy-websocket.conf;{{ end }}
        {{ if .Stream }}include {{.NginxPath}}/conf/conf.d/domains/includes/proxy-stream.conf;{{ end }}
        {{ end }}
    }
}
`

type ConfigData struct {
	Domain    string
	Target    string
	WS        bool
	GRPC      bool
	Stream    bool
	NginxPath string
	SitePath  string
	CertsPath string
}

// AddDomain creates a new domain configuration file
func AddDomain(domain, domainType, target string, ws, grpc, stream bool) error {
	var tmplStr string
	switch domainType {
	case "spa":
		tmplStr = SPATemplate
	case "proxy":
		tmplStr = ProxyTemplate
	default:
		return fmt.Errorf("unsupported domain type: %s", domainType)
	}

	tmpl, err := template.New("nginx").Parse(tmplStr)
	if err != nil {
		return fmt.Errorf("failed to parse template: %v", err)
	}

	filePath := filepath.Join(config.GetDomainsPath(), domain+".conf")
	f, err := os.Create(filePath)
	if err != nil {
		return fmt.Errorf("failed to create config file: %v", err)
	}
	defer f.Close()

	data := ConfigData{
		Domain:    domain,
		Target:    target,
		WS:        ws,
		GRPC:      grpc,
		Stream:    stream,
		NginxPath: config.GetNginxPath(),
		SitePath:  config.GetSitePath(),
		CertsPath: config.GetCertsPath(),
	}

	if err := tmpl.Execute(f, data); err != nil {
		return fmt.Errorf("failed to execute template: %v", err)
	}

	return nil
}
